### PR TITLE
Issue 159 import dao params

### PR DESCRIPTION
**Pull request by mrrobot16**

### CODE REVIEW

**Comment by dOrgJelli** [comment]
Looking great so far @cbrzn, I would work on the deserialization function next. Checkout the serialization logic here: https://github.com/dOrgTech/DAOcreator/blob/7aa8b5cffb8a976ab37f3c9c58cbc19c3511ca8d/src/lib/dependency/arc/index.ts#L7

We want to do the opposite of this function and move from the JSON to the DAOcreatorState object. The first step I would do to make this less error prone is create an interface for the JSON object that the migration project uses (htttps://github.com/daostack/migration):
```typescript
// warning psuedo code, may have errors
interface DAOMigrationParams {
  orgName: string;
  tokenName: string;
  tokenSymbol: string;
  VotingMachineParams: GenesisProtocolParams[];
  schemes: {
    ContributionReward?: boolean;
    GenericScheme?: boolean;
    SchemeRegistrar?: boolean;
  };
  ContributionReward?: {
    voteParams: number
  };
  GenericScheme?: {
    voteParams: number;
    targetContract: string;
  };
  SchemeRegistrar?: {
    voteRegisterParams: number;
    voteRemoveParams: number;
  };
  unregisterOwner: boolean;
  useUController: boolean;
  useDaoCreator: boolean;
  founders: Member[];
}
```

**Comment by cbrzn** [comment]
I have done the deserialization function (still need to add validations, first I want it to work). But it's not working at all right now, the schemes are added but the voting machine params are not. I'm pretty sure it's something on how the GenesisProtocolForm is being sent to all the schemes.

I would appreciate some feedback and if you want to have a chat with me i'm up to it :+1:

**Comment by dOrgJelli** [comment]
@cbrzn made a bunch of changes, you can see them here: https://github.com/dOrgTech/DAOcreator/pull/184/commits/e4419f5c6fdfb1cad0b27a777406361b71791278

I'm stopping my work on this here until I can pick this up again, have to go do something else unfortunately. The things that still have to be done are:
- properly serialize BN in `serialize(...)` and `deserialize(...)` in arc/types/migration.ts. If you import a config and export it, you can see in the resulting file that all BN types are broken. This is because the BN type isn't stored as simply a number, and toString must be called on each one. This attached file shows the error I'm referring to: [migration-params.txt](https://github.com/dOrgTech/DAOcreator/files/3598373/migration-params.txt)
- `updateForms` in DAOcreator/index isn't needed, as you can just use the `DAOForm` class' `fromState` function. See the code sample below:
```
form = new DAOForm();
form.fromState(deserializeState)
```
- Settings import should be styled like the other dialog for the "import members CSV". Also the the text within the dialog could use some refining.

**Comment by cbrzn** [comment]
@dOrgJelli it's done. let me know if you think there is some detail left to be done :+1:

**Comment by dOrgJelli** [comment]
Hey @cbrzn, nice work, I went through a made a few more changes you can see [here](https://github.com/dOrgTech/DAOcreator/pull/184/commits/cee232938919e4dda043e5a717a09749c17892a6).

Ran a bunch of tests and it's working well as far as I can tell. Gonna go ahead and merge this into master :raised_hands:!

**Pull request merged**
