### PR TITLE
Created Line Graphic component #286

### PR DESCRIPTION
**Pull request by Flash-Git**

### CODE REVIEW

**Comment by Flash-Git** [comment]
Thanks @cbrzn! I fixed the error with the hover, improved the update cycle and added some very basic styling to the hover.

> We should NOT show these graphics if the total reputation AND token is equal to zero (I can take care of that)

I believe the functionality you're describing is already implemented; only the graph with data to show will currently render.

If you mean the `Reputation Distribution` and `Token Distribution` divs then it would probably be worth moving the logic I used to count up the totals into the parent component and passing the values down as props. Happy to do that if you like!

**Comment by cbrzn** [comment]
> If you mean the Reputation Distribution and Token Distribution divs then it would probably be worth moving the logic I used to count up the totals into the parent component and passing the values down as props. Happy to do that if you like!

Absolutely, that's what I mean, then got for it sir! Let me know when it's ready @Flash-Git

**Comment by Flash-Git** [comment]
Should be good!

**Comment by cbrzn** [comment]
Just checked this, awesome work!! Merging now

**Pull request merged**
