### PR TITLE
Added scroll view to members

### PR DESCRIPTION
**Pull request by Flash-Git**
Hopefully handles #189.

### CODE REVIEW

**Comment by dOrgJelli** [comment]
Awesome @Flash-Git, one change I think we should make is making the max height of the scroll view a property, and if it isn't given then we shouldn't have the scroll view. That way the MembersEditor can be used in multiple contexts (constrained space, unconstrained space).

**Comment by Flash-Git** [comment]
> One change I think we should make is making the max height of the scroll view a property, and if it isn't given then we shouldn't have the scroll view.

Done! @dOrgJelli

**Comment by dOrgJelli** [comment]
Looks great @Flash-Git!

Also, now that you're a contributor, could you work out of a branch in the repo? That way I can push changes to the PR?

**Comment by Flash-Git** [comment]
Sure, which branch?

**Comment by dOrgJelli** [comment]
Just a branch based on the dOrgTech/DAOcreator repo instead of your fork.

**Pull request merged**
