### PR TITLE
Cotary Create: Implement functional Step 4

### PR DESCRIPTION
**Pull request by mrrobot16**
This PR is for issue #268

### CODE REVIEW

**Comment by cbrzn** [comment]
What's the state of this sir? Ready for a review?

**Comment by Flash-Git** [comment]
Not yet, I was trying really hard to reuse the existing Migrator code but after talking to Jordan it seems like it makes more sense to rewrite it from scratch.
I'm hoping to be done in a couple of days!

**Comment by Flash-Git** [comment]
There's some styling work that needs doing and I'd like to add some extra functionality but this is very much functional so I'm opening for review.

**Comment by mrrobot16** [comment]
@Flash-Git this is great mate!

I am merging it now :)

**Pull request merged**
