### PR TITLE
feat: notify network message implemented

### PR DESCRIPTION
**Pull request by cbrzn**

### CODE REVIEW

**Comment by orenyodfat** [comment]
this does not address #522 
it suppose to show to the user the current network she is logged in..,,and offer her to switch to other network from the networks supported to deploy on other networks.
Screen Shot 2020-11-30 at 0 02 59

- the best way will be that alchemy will pass to daocreator the supported networks list (using the same mechanism we are using for the BASE url)

**Comment by cbrzn** [comment]
@orenyodfat can you please explain how did you test it? Right now it is detecting in which network the user is connected from the provider

Please if that's not the case explain with more details how you want this functionality and we can change it as desired

**Comment by orenyodfat** [comment]
it still does not work as expected .
see 
https://github.com/daostack/alchemy/pull/2308#issuecomment-739417416 
it works ok for xdai though not for main.

**Comment by orenyodfat** [comment]
see https://github.com/dOrgTech/DAOcreator/issues/526 @cbrzn

**Comment by orenyodfat** [comment]
see #527 and #528 @cbrzn

**Pull request merged**
