### PR TITLE
 Cotary Create: Changes from feedback #423 

### PR DESCRIPTION
**Pull request by Flash-Git**
#423

### CODE REVIEW

**Comment by Flash-Git** [comment]
@cbrzn Could you help me with this? We want the blockie as an end adornment inside the input.

Link to [commit](https://github.com/dOrgTech/DAOcreator/pull/424/commits/22d562feff57b0ef77a5491e7e2353ad3f4ac65c).

**Comment by mrrobot16** [comment]
@Flash-Git i have just fixed a merge conflict.

**Comment by Flash-Git** [comment]
I already made that change in another branch.

**Comment by Flash-Git** [comment]
Everything but the blockie is done! Will figure that out in a bit

**Comment by Flash-Git** [comment]
Ready to merge!

**Pull request merged**
