### PR TITLE
Support for multiple notifications ++

### LINKED ISSUE #37: Support Multiple Notifications
Currently we only support one notification that's stored in the global app state (interface NotificationState in AppState.ts).

We should support multiple notifications popping up from multiple different sources within the app at a single time, without them overwriting each other.

### LINKED ISSUE #82: When the user is on a network that is not supported, inform the user of what networks are supported
When the user is on a network that is not supported by the DAOcreator we should inform the user of what networks are supported.

Right now the user just gets a "Network not supported" error.

### PR DESCRIPTION
**Pull request by sogasg**
FYI: Material-UI only supports showing one notification at a time (Material Design Guidelines). This solution uses the library uses [notistack](https://github.com/iamhosseindhv/notistack) which is recommended in the Material-UI documentation for this displaying multiple notifications at once.

closes #37
closes #82

### CODE REVIEW

**Comment by dOrgJelli** [comment]
LGTM, just one bug. When I tested it I couldn't close the notifications, and they didn't seem to disappear on their own.

**Comment by sogasg** [comment]
> Notifications didn't go away.

Did you create a new notification that did not have ’persist’ set to ’true’?

**Comment by dOrgJelli** [comment]
Oh okay gottit, the notifications I was testing with were at the deployment page. I was rejecting the transactions, which would cause a notification to show up, but it never went away.

**Comment by sogasg** [comment]
> Oh okay gottit, the notifications I was testing with were at the deployment page. I was rejecting the transactions, which would cause a notification to show up, but it never went away.

Aha, that notification is also persistent and are not closed.

**Pull request merged**
