### PR TITLE
Feat download csv template

### PR DESCRIPTION
**Pull request by mrrobot16**

### CODE REVIEW

**Comment by mrrobot16** [comment]
This PR is for issue https://github.com/dOrgTech/DAOcreator/issues/179

**Comment by orishim** [comment]
Great work!

One suggestion:
Instead of the button being next to the upload button inline with the member, I think the a button that says 'Download Template' should be to the right of the 'Upload File' button once you open up the upload file dialog.

**Comment by dOrgJelli** [comment]
@cbrzn nice work! I incorporated @orishim's suggestions, and moved the "MembersForm to CSV" logic into the Lib layer (out of the view) and also used the csv-stringify module instead of manually serializing it ourselves. You can see these changes in my latest commits.

Check it out locally and let me know if this looks go to you all @cbrzn @mrrobot16 @orishim :pray:

**Comment by mrrobot16** [comment]
@cbrzn @dOrgJelli it looks cool to me!! Good one!

**Pull request merged**
