### PR TITLE
CSS Fixes

### PR DESCRIPTION
**Pull request by dOrgJelli**

### CODE REVIEW

**Comment by dOrgJelli** [comment]
@cbrzn why are we adding all of these font files into the assets folder?

**Comment by dOrgJelli** [comment]
Also these changes bloats the package size by 3 MB... not sure why, please check

**Comment by cbrzn** [comment]
we were adding it because the mdb react css was importing it, after re-checking it we dont need this css because the font is being added by the bootstrap css; has been fixed now! @dOrgJelli

**Comment by cbrzn** [comment]
btw, the package size was 3mb because of the fonts added (the size of this folder was of 1.4mb) - lmk if this is enough sir

**Comment by dOrgJelli** [comment]
Looks great @cbrzn!

**Pull request merged**
