### PR TITLE
[WIP] Cotary Create: Adding basic support for the Ethereum Name Service #355

### PR DESCRIPTION
**Pull request by Flash-Git**
#355

### CODE REVIEW

**Comment by dOrgJelli** [comment]
@Flash-Git this has no code changes, so it doesn't look like it's actually ENS support. Going to close for now.

**Comment by Flash-Git** [comment]
I was asked to open pull requests on active issues because it's a lot easier to share and visualise progress this way than it is when looking at individual branches.

**Comment by dOrgJelli** [comment]
Oh whoops my bad, didn't know :P

**Comment by Flash-Git** [comment]
No problem! The web3 version had to be updated before work can begin because of the recent migration.

**Comment by Flash-Git** [comment]
On further examination this cannot be done from the UI and will require a lib change because of how we validate fields. Going to follow your lead and close this for now.

**Pull request closed without merging**
