### PR TITLE
Cotary Create: Master Branch 

### PR DESCRIPTION
**Pull request by mrrobot16**
This PR is for issue: https://github.com/dOrgTech/DAOcreator/issues/246

### CODE REVIEW

**Comment by mrrobot16** [comment]
Currently we are trying these 2 css component libraries:
https://chakra-ui.com
https://react-rainbow.firebaseapp.com

**Comment by mrrobot16** [comment]
This PR is for issue: https://github.com/dOrgTech/DAOcreator/issues/246

**Comment by Flash-Git** [comment]
I get an error in Stepper when reaching step 4. Happy to go after it if nobody else is working on it! @cbrzn @mrrobot16

**Comment by mrrobot16** [comment]
@Flash-Git what error are you talking about?

**Comment by cbrzn** [comment]
> @Flash-Git what error are you talking about?

Screenshot 2020-01-29 at 09 45 25

I think he means this error - But it has been fixed

**Comment by Flash-Git** [comment]
> > @Flash-Git what error are you talking about?
> 
> Screenshot 2020-01-29 at 09 45 25
> 
> I think he means this error - But it has been fixed

Yep! Don't worry about it @mrrobot16

**Comment by dOrgJelli** [comment]
Would you all say we're ready to merge into dev? @mrrobot16 @Flash-Git @cbrzn

**Pull request merged**
