### PR TITLE
DAOcreator for 2.0

### PR DESCRIPTION
**Pull request by cbrzn**
closes: #504

### CODE REVIEW

**Comment by cbrzn** [comment]
There's a problem and is that now `arc-experimental` (https://github.com/daostack/arc/blob/experimental-0.1.1-rc.23/package.json#L63) uses node 12.6.1  and in the dependencies of one of daostack packages (being exactly, in `web3-utils`  it expects a version lower), here’s the exact error:
```
error web3-utils@1.2.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <=11.15.0". Got "12.16.1"
error Found incompatible module.
```
When we run `yarn` to install the packages it get this error, and I think it’s because the entire packages version (of the stack) wasn’t updated correctly

**Comment by orenyodfat** [comment]
can you use web3-utils@1.2.9 ?

**Comment by orenyodfat** [comment]
Does this pr not suppose to be vs arc-experimental branch ?
The daocreator-ui-experimental suppose to be 1.1.4 as the latest one is 1.1.3

**Comment by cbrzn** [comment]
> Does this pr not suppose to be vs arc-experimental branch ?
The daocreator-ui-experimental suppose to be 1.1.4 as the latest one is 1.1.3

Yes, it is sir. Totally my bad, will create a new PR to make this cleaner

**Pull request closed without merging**
