### PR TITLE
Cotary Create: Load from localstorage bug

### PR DESCRIPTION
**Pull request by mrrobot16**
This pr is for issue #432

### CODE REVIEW

**Comment by Flash-Git** [comment]
This actually highlights that the modal only shows changes made up until the step that the user left at. Not ideal.

**Comment by dOrgJelli** [comment]
@Flash-Git @mrrobot16 please see how V1 solves this issue.

Instead of checking to see if what you loaded is "empty", you should instead never save an empty form: https://github.com/dOrgTech/DAOcreator/blob/88b42866cbcd2ab91701df9c7bda0d1c854e4e1a/packages/ui_v1/src/components/DAOcreator/index.tsx#L99-L117

**Comment by Flash-Git** [comment]
@dOrgJelli I didn't implement the loading to and from localstorage and while I don't think the current functionality was intentional I can see the benefit of having it work as it does right now.

Rather than progress being lost if you leave while you're in the middle of editing a step, it will be stored. On load, the app will drop you right back where you left off and behave as if you never left. i.e. You won't be able to progress back to the steps you already modified until after you edit the current one to pass validation. (This doesn't apply to the advanced editor).

Thoughts?

**Comment by Flash-Git** [comment]
Try this out @dOrgJelli, @mrrobot16

**Comment by mrrobot16** [comment]
@dOrgJelli @Flash-Git hey thanks for optimizing this.

**Comment by dOrgJelli** [comment]
Looks good to me!

**Pull request merged**
